Produce release artifacts in CI

diff --git a/.github/workflows/_build-macos.yml b/.github/workflows/_build-macos.yml
--- a/.github/workflows/_build-macos.yml
+++ b/.github/workflows/_build-macos.yml
@@ -75,14 +75,25 @@ jobs:
           export DYLD_LIBRARY_PATH="$(pwd)/dep/lib:$(pwd)/Release:$DYLD_LIBRARY_PATH"
           cmake --build . --config Release --target unittest --verbose
       - name: Generate binaries
-        if: ${{ inputs.weekly-deploy }}
         run: |
           export PATH="/usr/local/opt/ccache/libexec:$PATH"
           alias cmake="/usr/local/bin/gtimeout 40m /usr/local/bin/cmake"
           cd build
-          cmake --build . --config Release --target package -- -parallelizeTargets
+          max_tries=10
+          i=0
+          until cmake --build . --config Release --target package -- -parallelizeTargets; do
+            if [ $i -eq $max_tries ]; then
+              echo "Error: failed after ${max_tries} tries."
+              exit 1
+            fi
+          done
           ccache --cleanup
           ccache --show-stats || true
       - name: Upload binaries only
-        if: ${{ inputs.weekly-deploy }}
-        run: bash -c 'scp -vv -o ServerAliveCountMax=2 -o ServerAliveInterval=300 -o ConnectTimeout=120 -o ConnectionAttempts=5 build/FreeOrion_*_Test_MacOSX_*.dmg o01eg@frs.sourceforge.net:/home/frs/project/freeorion/FreeOrion/Test/'
+        uses: actions/upload-artifact@v4
+        if: inputs.os == 'macos-13' 
+        with:
+          name: weekly-artifacts-sf-macos-${{ github.run_number }}
+          path: build/FreeOrion_*_MacOSX_*.dmg
+          if-no-files-found: error
+          retention-days: 1
