Run unit test on Godot4

diff --git a/.github/workflows/_build-docker.yml b/.github/workflows/_build-docker.yml
--- a/.github/workflows/_build-docker.yml
+++ b/.github/workflows/_build-docker.yml
@@ -113,6 +113,19 @@ jobs:
         run: |
           docker run -v "$(pwd):/freeorion" -v "${{ runner.temp }}/ccache:/ccache_dir" -e CCACHE_DIR='/ccache_dir' -w /freeorion/ ${{ steps.prep.outputs.tagged_image }} /freeorion/build/godot --disable-render-loop --verbose -s --path godot addons/gut/gut_cmdln.gd -gdir=res://test/ -ginclude_subdirs -gexit
       - name: Run godot
+        if: ${{ matrix.godot == '4' }}
+        run: |
+          echo "::group::Reimport Godot4 project"
+          docker run -v "$(pwd):/freeorion" -v "${{ runner.temp }}/ccache:/ccache_dir" -e CCACHE_DIR='/ccache_dir' -w /freeorion/ ${{ steps.prep.outputs.tagged_image }} /freeorion/build/godot --headless --import --path godot4
+          echo "::endgroup::"
+          echo "::group::Test Godot4 project"
+          docker run -v "$(pwd):/freeorion" -v "${{ runner.temp }}/ccache:/ccache_dir" -e CCACHE_DIR='/ccache_dir' -w /freeorion/ ${{ steps.prep.outputs.tagged_image }} /freeorion/build/godot --headless --verbose -s --path godot4 addons/gut/gut_cmdln.gd -gdir=res://test/ -ginclude_subdirs -gexit 2>&1 | tee test_output.log
+          echo "::endgroup::"
+          if grep -E "ERROR:|Missing class_names:" test_output.log; then
+            echo "::error::Godot completed with code 0, but execution errors occurred!"
+            exit 1
+          fi
+      - name: Run godot
         if: ${{ matrix.image == 'manjaro' && false }} # Manjaro stopped to support Godot 3
         run: |
           docker run -v "$(pwd):/freeorion" -v "${{ runner.temp }}/ccache:/ccache_dir" -e CCACHE_DIR='/ccache_dir' -w /freeorion/ ${{ steps.prep.outputs.tagged_image }} /usr/bin/xvfb-run /freeorion/build/godot --no-window --disable-render-loop --video-driver GLES2 --verbose -s --path godot addons/gut/gut_cmdln.gd -gdir=res://test/ -ginclude_subdirs -gexit
